# Generated by Django 5.1.7 on 2025-03-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pre-solo', 'Pre-Solo'), ('post-solo', 'Post-Solo')], max_length=20)),
                ('number', models.CharField(blank=True, help_text='Exercise reference number', max_length=10)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingrecord',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='training_records', to='training_records.exercise'),
        ),
    ]
