# Generated by Django 5.1.7 on 2025-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0002_exercise_trainingrecord_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='is_solo',
            field=models.BooleanField(default=False, verbose_name='Solo Flight'),
        ),
    ]
