# Generated by Django 5.1.7 on 2025-03-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0005_alter_user_student_license_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingrecord',
            name='internal_comments',
        ),
    ]
