# Generated by Django 5.1.7 on 2025-03-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0006_remove_internal_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.CharField(choices=[('not_performed', 'Not Performed'), ('needs_improvement', 'Needs Improvement'), ('performed_well', 'Performed Well')], default='not_performed', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this exercise performance')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='training_records.exercise')),
                ('training_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_performances', to='training_records.trainingrecord')),
            ],
            options={
                'ordering': ('exercise__category', 'exercise__number'),
                'unique_together': {('training_record', 'exercise')},
            },
        ),
    ]
