# Generated by Django 5.1.7 on 2025-05-18 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0008_populate_exercise_performances'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundBriefingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Briefing Number')),
                ('name', models.CharField(max_length=100, verbose_name='Topic Name')),
                ('details', models.TextField(blank=True, verbose_name='Topic Details')),
            ],
            options={
                'verbose_name': 'Ground Briefing Topic',
                'verbose_name_plural': 'Ground Briefing Topics',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GroundBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('signed_off', models.BooleanField(default=False, verbose_name='Signed Off')),
                ('sign_off_date', models.DateField(blank=True, null=True, verbose_name='Sign Off Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_ground_briefings', to=settings.AUTH_USER_MODEL, verbose_name='Instructor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_briefings', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='training_records.groundbriefingtopic', verbose_name='Briefing Topic')),
            ],
            options={
                'verbose_name': 'Ground Briefing',
                'verbose_name_plural': 'Ground Briefings',
                'ordering': ['topic__number'],
                'unique_together': {('student', 'topic')},
            },
        ),
    ]
