# Generated by Django 5.1.7 on 2025-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0009_groundbriefingtopic_groundbriefing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseperformance',
            name='performance',
            field=models.CharField(choices=[('performed_well', 'Performed Well'), ('needs_improvement', 'Needs Improvement'), ('performed_badly', 'Performed Badly'), ('not_performed', 'Not Performed')], default='not_performed', max_length=20),
        ),
    ]
