# Generated by Django 5.1.7 on 2025-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0010_alter_exerciseperformance_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_expiration_date',
            field=models.DateField(blank=True, help_text='License expiration date', null=True),
        ),
    ]
