# Generated by Django 5.1.7 on 2025-09-27 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_records', '0011_user_license_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('instructor_weekly_digest', 'Weekly Pending Records Digest'), ('student_revision_needed', 'Student Record Needs Revision')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('training_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_records.trainingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type', 'training_record')},
            },
        ),
    ]
