name: Build and Push Docker Image
permissions:
  contents: read
  packages: write
  actions: read
on:
  push:
    branches: [ main ]  # Change this to your main branch name
  workflow_dispatch:    # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/studentlog:latest
            ghcr.io/${{ github.repository_owner }}/studentlog:${{ github.sha }}
