name: Build and Push Docker Image

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Keeps manual triggering option

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to check for changes

      - name: Check for changes since last run
        id: check_changes
        run: |
          # Get the timestamp of the last successful workflow run
          LAST_RUN=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$(basename $GITHUB_WORKFLOW)/runs?status=success&per_page=1" | \
            jq -r '.workflow_runs[0].created_at // "1970-01-01T00:00:00Z"')
          
          # Check if there are any commits since the last successful run
          CHANGES=$(git log --since="$LAST_RUN" --name-only --pretty=format: | grep -v '^$' | wc -l)
          
          if [ $CHANGES -gt 0 ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Found changes since last successful run, proceeding with build."
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected since last successful run, skipping build."
          fi

      - name: Set up Docker Buildx
        if: steps.check_changes.outputs.changes == 'true'
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        if: steps.check_changes.outputs.changes == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        if: steps.check_changes.outputs.changes == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/studentlog:latest
            ghcr.io/${{ github.repository_owner }}/studentlog:${{ github.sha }}